export enum SocialNetworkNames {
  discord = 'Discord',
  facebook = 'Facebook',
  fansly = 'Fansly',
  instagram = 'Instagram',
  linkedin = 'LinkedIn',
  onlyfans = 'OnlyFans',
  snapchat = 'Snapchat',
  telegram = 'telegram',
  tiktok = 'TikTok',
  twitch = 'twitch',
  twitter = 'Twitter', 
  whatsapp = 'WhatsApp',
  youtube = 'Youtube',
}
